name = "Arma Addon Template"
author = "FooBar Team"
prefix = "aam"
mainprefix = "z"
git_hash = 0

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]