name = "Smart Squad Behaviour"
author = "CatalpaBow"
prefix = "ssb"
mainprefix = "z"
git_hash = 0

[hemtt.launch.default]
workshop = [
    "450814997","2369477168",
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
] 
mission = "test.VR"